<?php
namespace HelloWorldService;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class hello
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'number',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'first_Name',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'last_Name',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'age',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $number = null;
    /**
     * @var string
     */
    public $first_Name = null;
    /**
     * @var string
     */
    public $last_Name = null;
    /**
     * @var int
     */
    public $age = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['number'])) {
                $this->number = $vals['number'];
            }
            if (isset($vals['first_Name'])) {
                $this->first_Name = $vals['first_Name'];
            }
            if (isset($vals['last_Name'])) {
                $this->last_Name = $vals['last_Name'];
            }
            if (isset($vals['age'])) {
                $this->age = $vals['age'];
            }
        }
    }

    public function getName()
    {
        return 'hello';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->number);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->first_Name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->last_Name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->age);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('hello');
        if ($this->number !== null) {
            $xfer += $output->writeFieldBegin('number', TType::I32, 1);
            $xfer += $output->writeI32($this->number);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->first_Name !== null) {
            $xfer += $output->writeFieldBegin('first_Name', TType::STRING, 2);
            $xfer += $output->writeString($this->first_Name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->last_Name !== null) {
            $xfer += $output->writeFieldBegin('last_Name', TType::STRING, 3);
            $xfer += $output->writeString($this->last_Name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->age !== null) {
            $xfer += $output->writeFieldBegin('age', TType::I32, 4);
            $xfer += $output->writeI32($this->age);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
