/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class hello : TBase
{
  private int _number;
  private string _first_Name;
  private string _last_Name;
  private int _age;

  public int Number
  {
    get
    {
      return _number;
    }
    set
    {
      __isset.number = true;
      this._number = value;
    }
  }

  public string First_Name
  {
    get
    {
      return _first_Name;
    }
    set
    {
      __isset.first_Name = true;
      this._first_Name = value;
    }
  }

  public string Last_Name
  {
    get
    {
      return _last_Name;
    }
    set
    {
      __isset.last_Name = true;
      this._last_Name = value;
    }
  }

  public int Age
  {
    get
    {
      return _age;
    }
    set
    {
      __isset.age = true;
      this._age = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool number;
    public bool first_Name;
    public bool last_Name;
    public bool age;
  }

  public hello() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Number = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              First_Name = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Last_Name = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              Age = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("hello");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.number) {
        field.Name = "number";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Number);
        oprot.WriteFieldEnd();
      }
      if (First_Name != null && __isset.first_Name) {
        field.Name = "first_Name";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(First_Name);
        oprot.WriteFieldEnd();
      }
      if (Last_Name != null && __isset.last_Name) {
        field.Name = "last_Name";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Last_Name);
        oprot.WriteFieldEnd();
      }
      if (__isset.age) {
        field.Name = "age";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Age);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("hello(");
    bool __first = true;
    if (__isset.number) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Number: ");
      __sb.Append(Number);
    }
    if (First_Name != null && __isset.first_Name) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("First_Name: ");
      __sb.Append(First_Name);
    }
    if (Last_Name != null && __isset.last_Name) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Last_Name: ");
      __sb.Append(Last_Name);
    }
    if (__isset.age) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Age: ");
      __sb.Append(Age);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

