//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./helloworld_types');
//HELPER FUNCTIONS AND STRUCTURES

var HelloWorldService_geHello_args = function(args) {
};
HelloWorldService_geHello_args.prototype = {};
HelloWorldService_geHello_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloWorldService_geHello_args.prototype.write = function(output) {
  output.writeStructBegin('HelloWorldService_geHello_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var HelloWorldService_geHello_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.hello(args.success);
    }
  }
};
HelloWorldService_geHello_result.prototype = {};
HelloWorldService_geHello_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.hello();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloWorldService_geHello_result.prototype.write = function(output) {
  output.writeStructBegin('HelloWorldService_geHello_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var HelloWorldServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
HelloWorldServiceClient.prototype = {};
HelloWorldServiceClient.prototype.seqid = function() { return this._seqid; };
HelloWorldServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

HelloWorldServiceClient.prototype.geHello = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_geHello();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_geHello();
  }
};

HelloWorldServiceClient.prototype.send_geHello = function() {
  var output = new this.pClass(this.output);
  var args = new HelloWorldService_geHello_args();
  try {
    output.writeMessageBegin('geHello', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

HelloWorldServiceClient.prototype.recv_geHello = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HelloWorldService_geHello_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('geHello failed: unknown result');
};
var HelloWorldServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
HelloWorldServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
HelloWorldServiceProcessor.prototype.process_geHello = function(seqid, input, output) {
  var args = new HelloWorldService_geHello_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.geHello.length === 0) {
    Q.fcall(this._handler.geHello.bind(this._handler)
    ).then(function(result) {
      var result_obj = new HelloWorldService_geHello_result({success: result});
      output.writeMessageBegin("geHello", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("geHello", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.geHello(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new HelloWorldService_geHello_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("geHello", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("geHello", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
