/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "helloworld_constants.h"

namespace HelloWorldService {

const helloworldConstants g_helloworld_constants;

helloworldConstants::helloworldConstants() {
}

} // namespace

