#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class hello(object):
    """
    Attributes:
     - number
     - first_Name
     - last_Name
     - age

    """


    def __init__(self, number=None, first_Name=None, last_Name=None, age=None,):
        self.number = number
        self.first_Name = first_Name
        self.last_Name = last_Name
        self.age = age

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.number = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.first_Name = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.last_Name = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.age = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('hello')
        if self.number is not None:
            oprot.writeFieldBegin('number', TType.I32, 1)
            oprot.writeI32(self.number)
            oprot.writeFieldEnd()
        if self.first_Name is not None:
            oprot.writeFieldBegin('first_Name', TType.STRING, 2)
            oprot.writeString(self.first_Name.encode('utf-8') if sys.version_info[0] == 2 else self.first_Name)
            oprot.writeFieldEnd()
        if self.last_Name is not None:
            oprot.writeFieldBegin('last_Name', TType.STRING, 3)
            oprot.writeString(self.last_Name.encode('utf-8') if sys.version_info[0] == 2 else self.last_Name)
            oprot.writeFieldEnd()
        if self.age is not None:
            oprot.writeFieldBegin('age', TType.I32, 4)
            oprot.writeI32(self.age)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(hello)
hello.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'number', None, None, ),  # 1
    (2, TType.STRING, 'first_Name', 'UTF8', None, ),  # 2
    (3, TType.STRING, 'last_Name', 'UTF8', None, ),  # 3
    (4, TType.I32, 'age', None, None, ),  # 4
)
fix_spec(all_structs)
del all_structs
