#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Hello; end

class Hello
  include ::Thrift::Struct, ::Thrift::Struct_Union
  NUMBER = 1
  FIRST_NAME = 2
  LAST_NAME = 3
  AGE = 4

  FIELDS = {
    NUMBER => {:type => ::Thrift::Types::I32, :name => 'number'},
    FIRST_NAME => {:type => ::Thrift::Types::STRING, :name => 'first_Name'},
    LAST_NAME => {:type => ::Thrift::Types::STRING, :name => 'last_Name'},
    AGE => {:type => ::Thrift::Types::I32, :name => 'age'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

